// This is used to provide better information for the "Daily Recommended" fractals.
// We only need the first 50 because the Daily Recommended fractals don't go above
// level 50.
const fractalNamesUnic = [
      {"en":"Volcanic", "es":"Fractal volcánico", "url":"https://wiki.guildwars2.com/wiki/Volcanic_Fractal"},
      {"en":"Uncategorized", "es":"Fractal sin clasificar", "url":"https://wiki.guildwars2.com/wiki/Uncategorized_Fractal"},
      {"en":"Snowblind", "es":"Fractal de la ceguera de la nieve", "url":"https://wiki.guildwars2.com/wiki/Snowblind_Fractal"},
      {"en":"Urban Battleground", "es":"Fractal del campo de batalla urbano", "url":"https://wiki.guildwars2.com/wiki/Urban_Battleground_Fractal"},
      {"en":"Swampland", "es":"Fractal del cenagal", "url":"https://wiki.guildwars2.com/wiki/Swampland_Fractal"},
      {"en":"Cliffside", "es":"Fractal del despeñadero", "url":"https://wiki.guildwars2.com/wiki/Cliffside_Fractal"},
      {"en":"Aquatic Ruins", "es":"Fractal de las Ruinas Acuáticas", "url":"https://wiki.guildwars2.com/wiki/Aquatic_Ruins_Fractal"},
      {"en":"Underground Facility", "es":"Fractal de la instalación subterránea", "url":"https://wiki.guildwars2.com/wiki/Underground_Facility_Fractal"},
      {"en":"Molten Furnace", "es":"Fractal de la fragua fundida", "url":"https://wiki.guildwars2.com/wiki/Molten_Furnace_Fractal"},
      {"en":"Molten Boss", "es":"Fractal de los jefes fundidos", "url":"https://wiki.guildwars2.com/wiki/Molten_Boss_Fractal"},
      {"en":"Deepstone", "es":"Fractal de Rocahonda", "url":"https://wiki.guildwars2.com/wiki/Deepstone_Fractal"},
      {"en":"Siren's Reef", "es":"Fractal del Arrecife de la Sirena", "url":"https://wiki.guildwars2.com/wiki/Siren%27s_Reef_Fractal"},
      {"en":"Chaos", "es":"Fractal del Caos", "url":"https://wiki.guildwars2.com/wiki/Chaos_Fractal"},
      {"en":"Aetherblade", "es":"Fractal de los filoetéreos", "url":"https://wiki.guildwars2.com/wiki/Aetherblade_Fractal"},
      {"en":"Thaumanova Reactor", "es":"Fractal del reactor taumanova", "url":"https://wiki.guildwars2.com/wiki/Thaumanova_Reactor_Fractal"},
      {"en":"Twilight Oasis", "es":"Fractal del Oasis del Crepúsculo", "url":"https://wiki.guildwars2.com/wiki/Twilight_Oasis_Fractal"},
      {"en":"Captain Mai Trin Boss", "es":"Fractal de la jefa Capitana Mai Trin", "url":"https://wiki.guildwars2.com/wiki/Captain_Mai_Trin_Boss_Fractal"},
      {"en":"Solid Ocean", "es":"Fractal del océano sólido", "url":"https://wiki.guildwars2.com/wiki/Solid_Ocean_Fractal"},
      {"en":"Nightmare", "es":"Fractal de la Pesadilla", "url":"https://wiki.guildwars2.com/wiki/Nightmare_Fractal"},
      {"en":"Shattered Observatory", "es":"Fractal del Observatorio Asolado", "url":"https://wiki.guildwars2.com/wiki/Shattered_Observatory_Fractal"},
      {"en":"Sunqua Peak", "es":"Pico de Sunqua", "url":"https://wiki.guildwars2.com/wiki/Sunqua_Peak_Fractal"}
];

var fractalList = {
    1: {"name":fractalNamesUnic[0], "ar": 0},
    2: {"name":fractalNamesUnic[1], "ar": 0},
    3: {"name":fractalNamesUnic[2], "ar": 0},
    4: {"name":fractalNamesUnic[3], "ar": 0},
    5: {"name":fractalNamesUnic[4], "ar": 0},
    6: {"name":fractalNamesUnic[5], "ar": 0},
    7: {"name":fractalNamesUnic[6], "ar": 0},
    8: {"name":fractalNamesUnic[7], "ar": 0},
    9: {"name":fractalNamesUnic[8], "ar": 0},
    10: {"name":fractalNamesUnic[9], "ar": 0},
    11: {"name":fractalNamesUnic[10], "ar": 0},
    12: {"name":fractalNamesUnic[11], "ar": 0},
    13: {"name":fractalNamesUnic[12], "ar": 0},
    14: {"name":fractalNamesUnic[13], "ar": 0},
    15: {"name":fractalNamesUnic[14], "ar": 0},
    16: {"name":fractalNamesUnic[15], "ar": 0},
    17: {"name":fractalNamesUnic[4], "ar": 0},
    18: {"name":fractalNamesUnic[16], "ar": 0},
    19: {"name":fractalNamesUnic[0], "ar": 0},
    20: {"name":fractalNamesUnic[17], "ar": 8},
    21: {"name":fractalNamesUnic[5], "ar": 10},
    22: {"name":fractalNamesUnic[8], "ar": 11},
    23: {"name":fractalNamesUnic[18], "ar": 13},
    24: {"name":fractalNamesUnic[19], "ar": 15},
    25: {"name":fractalNamesUnic[20], "ar": 17},
    26: {"name":fractalNamesUnic[6], "ar": 18},
    27: {"name":fractalNamesUnic[2], "ar": 20},
    28: {"name":fractalNamesUnic[0], "ar": 22},
    29: {"name":fractalNamesUnic[7], "ar": 24},
    30: {"name":fractalNamesUnic[12], "ar": 26},
    31: {"name":fractalNamesUnic[3], "ar": 27},
    32: {"name":fractalNamesUnic[4], "ar": 29},
    33: {"name":fractalNamesUnic[10], "ar": 31},
    34: {"name":fractalNamesUnic[14], "ar": 33},
    35: {"name":fractalNamesUnic[17], "ar": 34},
    36: {"name":fractalNamesUnic[1], "ar": 36},
    37: {"name":fractalNamesUnic[11], "ar": 38},
    38: {"name":fractalNamesUnic[12], "ar": 40},
    39: {"name":fractalNamesUnic[8], "ar": 42},
    40: {"name":fractalNamesUnic[9], "ar": 43},
    41: {"name":fractalNamesUnic[15], "ar": 45},
    42: {"name":fractalNamesUnic[16], "ar": 47},
    43: {"name":fractalNamesUnic[14], "ar": 49},
    44: {"name":fractalNamesUnic[1], "ar": 50},
    45: {"name":fractalNamesUnic[17], "ar": 52},
    46: {"name":fractalNamesUnic[13], "ar": 54},
    47: {"name":fractalNamesUnic[5], "ar": 56},
    48: {"name":fractalNamesUnic[18], "ar": 58},
    49: {"name":fractalNamesUnic[19], "ar": 59},
    50: {"name":fractalNamesUnic[20], "ar": 61},
    51: {"name":fractalNamesUnic[2], "ar": 63},
    52: {"name":fractalNamesUnic[0], "ar": 65},
    53: {"name":fractalNamesUnic[7], "ar": 67},
    54: {"name":fractalNamesUnic[11], "ar": 68},
    55: {"name":fractalNamesUnic[14], "ar": 70},
    56: {"name":fractalNamesUnic[4], "ar": 72},
    57: {"name":fractalNamesUnic[3], "ar": 74},
    58: {"name":fractalNamesUnic[8], "ar": 75},
    59: {"name":fractalNamesUnic[15], "ar": 77},
    60: {"name":fractalNamesUnic[17], "ar": 79},
    61: {"name":fractalNamesUnic[6], "ar": 81},
    62: {"name":fractalNamesUnic[1], "ar": 83},
    63: {"name":fractalNamesUnic[12], "ar": 84},
    64: {"name":fractalNamesUnic[14], "ar": 86},
    65: {"name":fractalNamesUnic[13], "ar": 88},
    66: {"name":fractalNamesUnic[3], "ar": 90},
    67: {"name":fractalNamesUnic[10], "ar": 91},
    68: {"name":fractalNamesUnic[2], "ar": 93},
    69: {"name":fractalNamesUnic[5], "ar": 95},
    70: {"name":fractalNamesUnic[9], "ar": 97},
    71: {"name":fractalNamesUnic[13], "ar": 99},
    72: {"name":fractalNamesUnic[16], "ar": 100},
    73: {"name":fractalNamesUnic[18], "ar": 102},
    74: {"name":fractalNamesUnic[19], "ar": 104},
    75: {"name":fractalNamesUnic[20], "ar": 106},
    76: {"name":fractalNamesUnic[6], "ar": 107},
    77: {"name":fractalNamesUnic[4], "ar": 109},
    78: {"name":fractalNamesUnic[11], "ar": 111},
    79: {"name":fractalNamesUnic[1], "ar": 113},
    80: {"name":fractalNamesUnic[17], "ar": 115},
    81: {"name":fractalNamesUnic[7], "ar": 116},
    82: {"name":fractalNamesUnic[14], "ar": 118},
    83: {"name":fractalNamesUnic[8], "ar": 120},
    84: {"name":fractalNamesUnic[10], "ar": 122},
    85: {"name":fractalNamesUnic[3], "ar": 123},
    86: {"name":fractalNamesUnic[2], "ar": 125},
    87: {"name":fractalNamesUnic[15], "ar": 127},
    88: {"name":fractalNamesUnic[12], "ar": 129},
    89: {"name":fractalNamesUnic[4], "ar": 131},
    90: {"name":fractalNamesUnic[9], "ar": 132},
    91: {"name":fractalNamesUnic[1], "ar": 134},
    92: {"name":fractalNamesUnic[0], "ar": 136},
    93: {"name":fractalNamesUnic[2], "ar": 138},
    94: {"name":fractalNamesUnic[5], "ar": 139},
    95: {"name":fractalNamesUnic[16], "ar": 141},
    96: {"name":fractalNamesUnic[13], "ar": 143},
    97: {"name":fractalNamesUnic[12], "ar": 145},
    98: {"name":fractalNamesUnic[18], "ar": 147},
    99: {"name":fractalNamesUnic[19], "ar": 148},
    100: {"name":fractalNamesUnic[20], "ar": 150}
}